Mission4_parkersm/Models/GradeCalcModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Mission4_parkersm.Models
{
    public class GradeCalcModel
    {
        [Required]
        [Range(0, 100)]
        public byte Assignments { get; set; }
        [Range(0, 100)]
        public byte GroupProject { get; set; }
        [Range(0, 100)]
        public byte Quizzes { get; set; }
        [Range(0, 100)]
        public byte Midterm { get; set; }
        [Range(0, 100)]
        public byte FinalExam { get; set; }
        [Range(0, 100)]
        public byte Intex { get; set; }

    }
}

Mission4_parkersm/Controllers/ChillingController.cs
using Microsoft.AspNetCore.Mvc;
using Mission4_parkersm.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission4_parkersm.Controllers
{
    public class ChillingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult GradeCalc()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GradeCalc(GradeCalcModel model)
        {
            return View();
        }
    }
}

Mission4_parkersm/Views/Chilling/GradeCalc.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Grade Calculator";
}
@model GradeCalcModel
<!--This is the Grade Calc that takes the inputs and assigns them to and ID to send to the jquery in the gradeCalc.js file-->
<h1>Grade Calculator</h1>
<br />
<form method="post">
    <label>Assignments:</label>
    <input id="assignments" asp-for="Assignments" /><br /><br />
    <label>Group Project:</label>
    <input id="groupProject" asp-for="GroupProject" /><br /><br />
    <label>Quizzes:</label>
    <input id="quizzes" asp-for="Quizzes" /><br /><br />
    <label>Midterm:</label>
    <input id="midterm" asp-for="Midterm" /><br /><br />
    <label>Final Exam:</label>
    <input id="finalExam" asp-for="FinalExam" /><br /><br />
    <label>INTEX:</label>
    <input id="intex" asp-for="Intex" /><br /><br />
    <input id="submit" type="submit" value="Submit Grades" />
    <div asp-validation-summary="All"></div>
</form>
<br />
<!--This is where the grade from the gradeCalc.js file is returned-->

<script src="@Url.Content("~/js/gradeCalc.js")" type="text/javascript"></script>

Mission4_parkersm/Views/Chilling/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Parker Smith's Website";
}


<!--This is the body with info about me and other items-->
<h1>Parker Smith</h1>
<br />
<br />
<h4>I love traveling around the world!</h4>
<p>This is my friend and me in Mexico City at the Teotihuacan Pyramids!</p>
<img src="img/traveling.jpeg" width="500" />
<br />
<br />
<br />
<h4>Most Interesting Jobs to Me!</h4>
<ul>
    <li>Software Developer</li>
    <li>Cloud Developer</li>
    <li>Data Analyst</li>
</ul>
<br />
<br />
<p>
    During this class I hope to learn enough C# to help further my goal of being a weapon in the <br />
    programming world. My goals are to be on top on assignments and not do them the same day they<br />
    are due and be fully prepared to work on the next one during class
</p>
<br />
<br />

Mission4_parkersm/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />
    <!--This is where I link the css and bootstrap and also add an image to my title-->
    <link href="@Url.Content("~/css/designs.css")" rel="stylesheet" />
    <link href="@Url.Content("~/lib/bootstrap/css/bootstrap.min.css")" rel="stylesheet" />
    <title>@ViewData["Title"]</title>
    <link rel="icon" type="image/x-icon" href="@Url.Content("~/img/Icon_Bird_512x512.png")">
</head>
<body>
    <nav>
        <a asp-controller="Chilling" asp-action="Index">Home</a>
        <a asp-controller="Chilling" asp-action="GradeCalc">Grade Calculator</a>
    </nav>

    <div>
        @RenderBody()
    </div>

    <footer>This is the footer</footer>
    <script src="@Url.Content("~/lib/jquery/jquery-3.6.3.min.js")"></script>
</body>
</html>